@rem
@rem Gradle startup script generated by Gradle.
@rem This wrapper uses the repository-local Gradle distribution.
@rem

@echo off
setlocal

set "APP_HOME=%~dp0"
set "JAVA_EXE=%JAVA_HOME%\bin\java.exe"

if not "%JAVA_HOME%"=="" if exist "%JAVA_EXE%" goto execute
set "JAVA_EXE=java.exe"
where java.exe >NUL 2>&1
if %ERRORLEVEL% EQU 0 goto execute

echo ERROR: Java was not found. Please install Java 21 or set JAVA_HOME. 1>&2
exit /b 1

:execute
"%JAVA_EXE%" -Xmx64m -Xms64m -Dorg.gradle.appname=%~nx0 -classpath "%APP_HOME%gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain %*
set "EXIT_CODE=%ERRORLEVEL%"
endlocal & exit /b %EXIT_CODE%
