#!/bin/sh

# Gradle startup script generated by Gradle.
# This wrapper intentionally uses the repository-local Gradle distribution.

APP_HOME=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) || exit 1
JAVACMD="${JAVA_HOME:+$JAVA_HOME/bin/}java"

if [ ! -x "$JAVACMD" ] && ! command -v java >/dev/null 2>&1; then
  echo "ERROR: Java was not found. Please install Java 21 or set JAVA_HOME." >&2
  exit 1
fi

if [ ! -x "$JAVACMD" ]; then
  JAVACMD=java
fi

exec "$JAVACMD" -Xmx64m -Xms64m -Dorg.gradle.appname="$(basename "$0")" -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
